### ISSUE TITLE
Not able to set profile location

### ISSUE THREAD

**Issue by FrostyNick** [ryanccn/nyoom#103]
Using:
- [nyoom-x86_64-unknown-linux-musl-static v0.7.5](https://github.com/ryanccn/nyoom/releases/download/v0.7.5/nyoom-x86_64-unknown-linux-musl-static) binary since I have x86_64 compatible computer.
- EndeavorOS (Arch-based distro)

When I run:
`nyoom profile /home/nicholas/.librewolf/dsiaofiohdsiuhgiuhgiudsgds.default/`
or
`nyoom add mimipile github:mimipile/firefoxCSS`

Both commands have the same response:
```txt
Error: 
   0: No such file or directory (os error 2)

Location:
   src/config.rs:94

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  <empty backtrace>
```

`nyoom --version` returns `nyoom 0.7.4` and help is displayed as it should.

**Comment by ryanccn** [comment]
Fixed in https://github.com/ryanccn/nyoom/commit/3ac3cede053aca01289bed07f9f0bdff41339819!

**Comment by jacksongoode** [comment]
Is there a possibility to do an automatic profile detection? 

Given that items within the profile directory get modified whenever a user interacts with them or starts a Firefox session, it should be easy to detect either the last profile that was modified.

In the first setup you could instruct the user to open a Firefox session that they want themed and then have them run the CLI to detect it.
