### ISSUE TITLE
[Feature] Update/apply while browser is running

### ISSUE THREAD

**Issue by jacksongoode** [ryanccn/nyoom#138]
Wondering if there's someway the tool can apply updates/new themes or configs while the browser is still running? Not sure if you've attempted this but I don't think making direct changes to the userChrome will have any affect anyway until the browser restarts.

**Comment by ryanccn** [comment]
nyoom also potentially edits `user.js` and making changes to that while the browser is running could be dangerous (I broke my Firefox profile once doing just that)
